CREATE TABLE IF NOT EXISTS categorias(
    id UUID PRIMARY KEY,
    nombre VARCHAR(255) UNIQUE NOT NULL,
    fecha_alta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    fecha_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    activa BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS funkos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    precio DECIMAL(10, 2) NOT NULL,
    fecha_alta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    fecha_modificacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    borrado BOOLEAN NOT NULL DEFAULT FALSE,
    descripcion VARCHAR(255),
    fecha_de_fabricacion DATE,
    categoria_id UUID,
    FOREIGN KEY (categoria_id) REFERENCES categorias(id) ON DELETE SET NULL
);